
name: Ping Deploy

on:
  push:
    branches: [ testnet ]
  pull_request:
    branches: [ testnet ]

jobs:
  deploy:
    name: Ping deploy
    runs-on: testnet 
    steps:
    - name: print
      run: echo ${GITHUB_REF#refs/heads/}
    - name: Git Checkout Latest
      uses: actions/checkout@v2
      
    - name: Install
      run: yarn install

    - name: Build
      run: yarn run vue-cli-service build

    - name: Deploy
      run: cp -rf ./dist/* /var/www/html/